name: Planora CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Backend setup
      - name: Install backend dependencies
        working-directory: BEplanora
        run: npm ci

      - name: Create backend .env file
        working-directory: BEplanora
        run: |
          echo "PORT=5000" > .env
          echo "MONGODB_URI=mongodb://127.0.0.1:27017/planora_test" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET || 'test-jwt-secret-key' }}" >> .env
          echo "TEST_ADMIN_FIRSTNAME=John" >> .env
          echo "TEST_ADMIN_LASTNAME=Doe" >> .env
          echo "TEST_ADMIN_EMAIL=john.doe@example.com" >> .env
          echo "TEST_ADMIN_PASSWORD=Password123!" >> .env

      # Frontend setup
      - name: Install frontend dependencies
        working-directory: FEplanora
        run: npm ci --omit=optional
        continue-on-error: false

      - name: Build frontend
        working-directory: FEplanora
        run: npm run build
        env:
          VITE_API_URL: http://localhost:5000

      # Run tests
      - name: Run backend tests
        working-directory: BEplanora
        run: npm test
        env:
          MONGODB_URI: mongodb://127.0.0.1:27017/planora_test
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NODE_ENV: test

      - name: Run frontend tests
        working-directory: FEplanora
        run: npm test
        env:
          CI: true

      # Linting
      - name: Lint frontend
        working-directory: FEplanora
        run: npm run lint || true
        continue-on-error: true

      # E2E Tests
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@master

      - name: Start backend server
        working-directory: BEplanora
        run: |
          npm start &
          sleep 10
        env:
          MONGODB_URI: mongodb://127.0.0.1:27017/planora_test
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: 5000

      - name: Start frontend server
        working-directory: FEplanora
        run: |
          npx vite preview --port 5173 --strictPort &
          sleep 10

      - name: Run E2E tests
        working-directory: FEplanora
        run: npm run test:e2e || echo "E2E tests not configured"
        continue-on-error: true
        env:
          CI: true
          TEST_BASE_URL: http://localhost:5173

      # Cleanup
      - name: Cleanup processes
        if: always()
        run: |
          pkill -f "node" || true
          pkill -f "vite" || true
